get http://localhost:3001/orders
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFPdkM2T05rY0dpT2NKQUZWZTZSTSJ9.eyJpc3MiOiJodHRwczovL29yZGVyc21hbmFnZXIudXMuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA1NDQwNDA5MjkzMDM3NjI0NDcwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMSIsImh0dHBzOi8vb3JkZXJzbWFuYWdlci51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjIyNTU3MzY0LCJleHAiOjE2MjI2NDM3NjQsImF6cCI6ImxMb3FLUUJXaFhYQ0VUczhCSTlMMjR5QnIwQjNVZGFUIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.siEzl4EoskoIc7bIcNqVP81vIciowOt87fqxnxBtxROWTkJc5Ah9_Gt8gTIulgIKuVY5Z--tTmaVk4_TpETPEovsWfvjmVaiK8ET0JIGgjcTBOc73wYFema6m2WdfjAvkOgkF4O0zupb-I2weT2F1zWq0HlTokBH7FP7qe9XBVKEJngeyxdxkINBQB032h5FnRVNajLOgY1tnWgNeQ4oUP1t6G0pKp2o1Bigq90KTm94ub3MZIAqRZLtee-IYQrkUXjTBjI-QHhoeCzR-4BfJ8djEehxPnulH4Q3-AU49jemIT9I-45N3rxathFJByqnEhz3Plq1wNoJFG-beUCYkg
